module.exports = {
    devServer:{
      host:'localhost',
      port:8080,
      proxy:{
        '/api':{
          target:'http://localhost:5000',
          changeOrigin:true,
          pathRewrite:{
            '/api':''
          }
        }
      }
    },
    productionSourceMap:true,
    chainWebpack:(config)=>{
      config.plugins.delete('prefetch');
    }
  }